
run_test:
  tags:
    - docker
  image: python:3.11-alpine
  before_script:
    - pip install flask
    - pip install jinja2
  script:
    - python hello.py &

pages:      
  tags:
    - docker
  image: python:3.11-alpine
  before_script:
    - pip install jinja2
    - pip install pandas
  script:
    - mkdir public
    - python Chart_template.py
    - mv *.html ./public
  artifacts:
    paths:
      - public
  only:
    - main

