
run_test:
  tags:
    - docker
  image: python:3.11-alpine
  before_script:
    - pip install flask
    - pip install jinja2
  script:
    - python hello.py &

pages:      
  tags:
    - docker
  image: python:3.11-alpine
  before_script:
    - pip install jinja2
    - pip install pandas
  script:
    - mkdir public
    - python Chart_template.py --files ./yambo/results.dat=Nodes,walltime,second,sth_kernel ./yambo/result1.dat=Nodes,walltime,second,electrons ./yambo/result0.dat=Nodes,walltime,second,electrons
    - mv *.html ./public
    - cp *.jpg ./public
    - cp *.png ./public
  artifacts:
    paths:
      - public
  only:
    - main

