
run_test:
  tags:
    - docker
  image: python:3.11-alpine
  before_script:
    - pip install flask
    - pip install flask-wtf
  script:
    - mkdir public
    - pip freeze > req.dat
    - mv req.dat ./public
    - python hello.py
    #- google-chrome http://127.0.0.1:5000/
    #- cd public && touch firstfile
      

